// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWVP6sol7J_rTqfujajWFV_QslVy48jR8',
    appId: '1:730023436732:web:c771508b106d16d8790bb9',
    messagingSenderId: '730023436732',
    projectId: 'gymanager-aa65d',
    authDomain: 'gymanager-aa65d.firebaseapp.com',
    storageBucket: 'gymanager-aa65d.firebasestorage.app',
    measurementId: 'G-PTE9BBBW97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5wJO0hC4uLwleDUxesKlQ93Mgawjuv6I',
    appId: '1:730023436732:android:b8edea1b9471ca73790bb9',
    messagingSenderId: '730023436732',
    projectId: 'gymanager-aa65d',
    storageBucket: 'gymanager-aa65d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD64G5HMKMIrZBzS9ETvpPyoW3M9Lf5PPc',
    appId: '1:730023436732:ios:1201b0d3a69f7da4790bb9',
    messagingSenderId: '730023436732',
    projectId: 'gymanager-aa65d',
    storageBucket: 'gymanager-aa65d.firebasestorage.app',
    iosBundleId: 'com.example.gymanager',
  );
}
